### ISSUE TITLE
Action for testing endpoints

### ISSUE THREAD

**Issue by Yannx79** [Yannx79/Learning-Platform-Reactive-API#1]
```yml
name: Test Endpoints

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-endpoints:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Collection
        run: |
          newman run path/to/your-collection.json \
            -e path/to/your-environment.json \
            --reporters cli
```
